server:
  port: ${PORT:8080}

spring:
  application:
    name: interviewprep

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

openai:
  api-key: ${OPENAI_API_KEY:}

external:
  challenge:
    api:
      base-url: ${EXTERNAL_CHALLENGE_API_BASE_URL:}
      import-path: ${EXTERNAL_CHALLENGE_API_IMPORT_PATH:}
      api-key: ${EXTERNAL_CHALLENGE_API_KEY:}
      api-host: ${EXTERNAL_CHALLENGE_API_HOST:}
      enabled: ${EXTERNAL_CHALLENGE_API_ENABLED:false}